services:
  postgres-dw:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow-3-dbt_c6b95b_airflow

volumes:
  postgres_data:

networks:
  airflow-3-dbt_c6b95b_airflow:
    external: true
